### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by ShotaroKataoka** [ShotaroKataoka/ShotaroKataoka.github.io#1]
```yaml
blog_title: ShotaroKataoka.github.io
site_introduction: かたおかの個人ブログです。やったこと、メモなど備忘録的に残しています。ほぼ日記みたいなものです。
copylight_name: ShotaroKataoka
copylight_url: https://github.com/ShotaroKataoka
root_url: https://ShotaroKataoka.github.io
issues_page_url: https://github.com/ShotaroKataoka/ShotaroKataoka.github.io/issues
favicon_image_url: https://user-images.githubusercontent.com/42331656/175220729-c255f8b0-e709-4efc-a8e6-dc2e29a92c35.png
author_name: かたおか
author_introduction: |-
  かたおかです。
  アイコンはみかん。
avatar_image_url: https://user-images.githubusercontent.com/42331656/175183205-06dc6033-af20-44b9-ae3d-c3e68770a1f3.png
sns:
  - name: GitHub
    url: https://github.com/ShotaroKataoka
  - name: Twitter
    url: https://twitter.com/KataokaShotaro
  - name: Facebook
    url: https://www.facebook.com/profile.php?id=100014221270440
  - name: LinkedIn
    url: https://www.linkedin.com/in/shotarokataoka/
  - name: Instagram
    url: https://www.instagram.com/s.kataoka_/?hl=ja
```
