### ISSUE TITLE
第１回長岡技術フォーラムで登壇

### ISSUE THREAD

**Issue by ShotaroKataoka** [ShotaroKataoka/ShotaroKataoka.github.io#10]
```yaml
# 必要に合わせてコメントアウトを外して記載してください

# 記事の説明文(無い場合は本文先頭200文字を使用)
#ogp_description:

# サムネイル画像のテーマ -> 'default' or 'upload'
thumbnail_theme: upload

# サムネイル画像の背景画像(1280x670px推奨, なくてもOK)
thumbnail_image_url: https://user-images.githubusercontent.com/42331656/188040680-e97f000c-0480-450f-89ed-114687c255b4.jpg

# 予約投稿の日時(無い場合は現在時刻を使用)
posted_at: 2022-07-28 09:00
```

2022年7月27日に新潟県長岡市で「長岡技術フォーラム～ 次世代 ICT 技術者を生み出す イノベーション都市 長岡～」が開催され、長岡発AIベンチャー 株式会社マヨラボの代表取締役として招待を受け講演をしました。

## フォーラムの概要
このフォーラムは長岡市とNTT東日本様の「イノベーション都市 長岡」実現に向けた連携協定の締結記念として開催されたイベントです。
フォーラムでは長岡市のITベンチャー3社とNTT東日本様から3名が講演を行いました。

![image](https://github.com/ShotaroKataoka/ShotaroKataoka.github.io/assets/42331656/3e5f607d-73cb-4102-a57c-164af2c0127f)

## 感想
お昼ごはんの時間にNTT 東日本 特殊局員としていらっしゃっていた登大遊先生とお話することができました！
ネットワークやクラウド技術のかなりディープな内容から今後の日本のIT教育についてまでかなり幅広いトピックでディスカッションでき、とても楽しい時間を過ごすことができました。
登先生めちゃくちゃ面白い人だった……。

![image](https://github.com/ShotaroKataoka/ShotaroKataoka.github.io/assets/42331656/9b01e34a-b08a-4292-9b0e-bb0b5fa8d908)

控室の写真
（ちゃんと控室があるイベント初めてだったので緊張しました。。。）
