### ISSUE TITLE
株式会社マヨラボを起業・CEOに就任

### ISSUE THREAD

**Issue by ShotaroKataoka** [ShotaroKataoka/ShotaroKataoka.github.io#11]
```yaml
# 必要に合わせてコメントアウトを外して記載してください

# 記事の説明文(無い場合は本文先頭200文字を使用)
#ogp_description:

# サムネイル画像のテーマ -> 'default' or 'upload'
thumbnail_theme: upload

# サムネイル画像の背景画像(1280x670px推奨, なくてもOK)
thumbnail_image_url: https://github.com/ShotaroKataoka/ShotaroKataoka.github.io/assets/42331656/2eedaac2-fc76-40ac-9e7a-78eb3b197cb1


# 予約投稿の日時(無い場合は現在時刻を使用)
#posted_at: 2021-02-25 09:00
```

https://mayolab.co.jp/

株式会社マヨラボを設立し、代表取締役CEOに就任しました。
マヨラボは「人とAIをつなぎ、人類の進歩をささえる」ことを目指すAI研究開発ベンチャー企業です。
今後、製造業界との共同研究を通してAIによる前進を模索していきます。
