### ISSUE TITLE
未踏AIフロンティアプログラムで1年間研究した

### ISSUE THREAD

**Issue by ShotaroKataoka** [ShotaroKataoka/ShotaroKataoka.github.io#12]
```yaml
# 必要に合わせてコメントアウトを外して記載してください

# 記事の説明文(無い場合は本文先頭200文字を使用)
#ogp_description:

# サムネイル画像のテーマ -> 'default' or 'upload'
thumbnail_theme: upload

# サムネイル画像の背景画像(1280x670px推奨, なくてもOK)
thumbnail_image_url: https://github.com/ShotaroKataoka/ShotaroKataoka.github.io/assets/42331656/84f327e9-bb44-4d93-b650-5db704507405

# 予約投稿の日時(無い場合は現在時刻を使用)
posted_at: 2020-02-22 09:00
```

NEDOによる未踏事業AIフロンティアプログラムに採択され、「ディープラーニングを用いた工場内動画からの作業検出」に関する研究を行いました。

> **[AIフロンティアプログラム](https://www.mitou.org/projects/ai_frontier/index_1nd.html)について**
NEDOの研究開発事業の一環として一般社団法人未踏が実施するAI技術を活用した新しいアプリケーションを創出できるような人材を育成するための人材育成プログラム。
プロジェクトマネージャ：北野 宏明さん (株式会社ソニーコンピュータサイエンス研究所 代表取締役社長 / 所長)
メンター：清水 亮さん (ギリア株式会社 代表取締役社長)、吉崎 航さん (アスラテック株式会社 取締役 / チーフロボットクリエイター / V-Sido開発者)

メンターの吉崎航さん(未踏スーパークリエータ／V-Sido OS開発者)からの指導を受けながらプログラミングに取り組みました。
他の未踏クリエータとの合宿なども行い、非常に学ぶことの多い1年間を過ごしました。

![image](https://github.com/ShotaroKataoka/ShotaroKataoka.github.io/assets/42331656/94c49d8b-8254-4272-a9ed-64c396f3b58a)

最終成果報告会は秋葉原UDXの大きい会場で実施し、1年間の成果を発表しました。
経産省からプロジェクト成果を認められAIフロンティアパスファインダー(未踏スーパークリエータに相当)として認定されました。
