### ISSUE TITLE
クラウドファンディングを開始！！したよ！

### ISSUE THREAD

**Issue by ShotaroKataoka** [ShotaroKataoka/ShotaroKataoka.github.io#19]
```yaml
# 必要に合わせてコメントアウトを外して記載してください

# 記事の説明文(無い場合は本文先頭200文字を使用)
#ogp_description:

# サムネイル画像のテーマ -> 'default' or 'upload'
thumbnail_theme: upload

# サムネイル画像の背景画像(1280x670px推奨, なくてもOK)
thumbnail_image_url: https://github.com/ShotaroKataoka/ShotaroKataoka.github.io/assets/42331656/5495db09-01dd-40e5-a4c7-06a1db4c473e


# 予約投稿の日時(無い場合は現在時刻を使用)
posted_at: 2024-01-16 09:00
```

[チームWeareableが米Indiegogoで挑戦しているクラウドファンディング](https://www.indiegogo.com/projects/synthevery-a-new-instrument-all-u-need-is-motion/x/36534099#/)が開始わずか3日間で目標金額100%を達成！！
現在は次の目標をロックオン！してます！
新潟から世界への挑戦！

Syntheveryは日常の"動き"に音楽を融合する新しいウェアラブル楽器。
めちゃめちゃ面白いデバイスです！

<div style="display: flex; justify-content: center; width: 100%;"><div style="position: relative; width: 100%; max-width: 560px; height: 0; padding-bottom: 56.25%;"><iframe src="https://www.youtube.com/embed/ggNu_f9FkfU?si=7CHpTHZhb-jfyii3&rel=1" title="YouTube video player" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div></div>
