### ISSUE TITLE
ビジネスアイデアコンテストでグランプリを受賞しました

### ISSUE THREAD

**Issue by ShotaroKataoka** [ShotaroKataoka/ShotaroKataoka.github.io#20]
```yaml
# 必要に合わせてコメントアウトを外して記載してください

# 記事の説明文(無い場合は本文先頭200文字を使用)
#ogp_description:

# サムネイル画像のテーマ -> 'default' or 'upload'
thumbnail_theme: upload

# サムネイル画像の背景画像(1280x670px推奨, なくてもOK)
thumbnail_image_url: https://github.com/ShotaroKataoka/ShotaroKataoka.github.io/assets/42331656/ab54d2ad-f9e5-4470-8787-1d9c7bb9ab07

# 予約投稿の日時(無い場合は現在時刻を使用)
posted_at: 2018-12-02 09:00
```

[「えちご想発xTech」（学生ICTビジネスアイデアコンテスト2018 in 長岡）](http://www.ict-echigo.jp/news/public/detail/ID/96/td/)に出場し、グランプリを受賞しました。

![受賞の様子](https://github.com/ShotaroKataoka/ShotaroKataoka.github.io/assets/42331656/ab54d2ad-f9e5-4470-8787-1d9c7bb9ab07)
