### ISSUE TITLE
これ何のファイル？を無くすためのCLIツールを作った

### ISSUE THREAD

**Issue by ShotaroKataoka** [ShotaroKataoka/ShotaroKataoka.github.io#21]
```yaml
# 必要に合わせてコメントアウトを外して記載してください

# 記事の説明文(無い場合は本文先頭200文字を使用)
#ogp_description:

# サムネイル画像のテーマ -> 'default' or 'upload'
thumbnail_theme: default

# サムネイル画像の背景画像(1280x670px推奨, なくてもOK)
#thumbnail_image_url: 

# 予約投稿の日時(無い場合は現在時刻を使用)
posted_at: 2020-07-30 09:00
```

## 何のためのツールか？

3年前に書いたプログラムを見返して、こういうことはありませんか？

![image](https://github.com/ShotaroKataoka/ShotaroKataoka.github.io/assets/42331656/4325278c-4339-4fd5-a585-81049a5099a2)

<font size='6'>どれが何のファイル？？？</font>

<br/><br/>

ソースコードならなんとなく推測できますが、
実験ログとかは**結構しんどい**です。
ログの命名規則には従いたいけど、それだと人間的にはわかりづらかったりするんですね。

![image](https://github.com/ShotaroKataoka/ShotaroKataoka.github.io/assets/42331656/ec9bd9e7-c7db-4852-acdf-5b85483357ff)

<br/>

これを解決するために、、、

![image](https://github.com/ShotaroKataoka/ShotaroKataoka.github.io/assets/42331656/62d0e165-ae0e-4f23-a3e3-a814c68e1622)

![image](https://github.com/ShotaroKataoka/ShotaroKataoka.github.io/assets/42331656/67b784c1-9a61-4e05-84a4-3911cb8e5ec9)

こうします。
カラフルでかわいいですね。

<br/>

こんな感じで説明文をつけられるCLIツール[ls-Improved](https://github.com/ShotaroKataoka/ls-Improved)を開発しました。

## ls-Improved
Pythonで開発しており、PyPIから`pip install ls-Improved`でインストールできます。

こんな感じの用途を想定しています。
- 機械学習等の実験パラメータの整理
![image](https://github.com/ShotaroKataoka/ShotaroKataoka.github.io/assets/42331656/8e69dda2-c5e8-4d5a-9585-9940f3c5bac4)

- チーム開発におけるディレクトリ構造の共有
![image](https://github.com/ShotaroKataoka/ShotaroKataoka.github.io/assets/42331656/1ba01fc6-bb89-4cd7-9de7-edd7c4f5336d)

- ターミナル映え
![image](https://github.com/ShotaroKataoka/ShotaroKataoka.github.io/assets/42331656/7f706f96-6371-4c0a-b24b-f306ab09bc36)

## 今後
実行速度と可搬性のためにバイナリツールにリプレースすることを計画しています。
現在はRustでα版を開発しており、近いうちに正式版も出せるかも。

<br/>

バイナリ化できればチーム開発のリポジトリでツールごと共有できます。
そうすれば、未インストールのメンバーとも説明文を共有できるようになるので便利になると思ってます。
