### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by ShotaroKataoka** [ShotaroKataoka/ShotaroKataoka.github.io#3]
```yaml
site_description: |-
    ## このサイトの紹介

    このサイトはRibbonCMSで作成しました。
    画像を含めたすべての情報や記事はGitHub Issuesによって更新されています
author_description_detail: |-
    25卒の博士課程学生。AI・機械学習の産業応用が専門です。
    工場内動画解析や特許出願書類のNLPについて研究しています。
    [未踏修了生](https://scrapbox.io/mitou-meikan/%E7%89%87%E5%B2%A1_%E7%BF%94%E5%A4%AA%E9%83%8E)／経産省からAIフロンティアパスファインダーとして認定されました。

    趣味：個人開発／ボードゲーム・謎解き／カラオケ／開発環境カスタマイズ
skills_data:
  - title: Python
    description: |-
      8年以上の経験。研究等の実務で使用。
      データ分析 / 機械学習，スクレイピング，CUI / GUIツール開発，LINE / slackボット開発など。
    image_url: https://user-images.githubusercontent.com/42331656/168748967-d8aeac42-4035-425e-809a-3b7687f794a5.png
    tags:
      - Programming language
      - Data Science
  - title: PyTorch
    description: |-
      5年程度の研究・インターンでの実務経験。
      論文の追実験や独自アーキテクチャモデルの構築をします。
      主な研究対象：動画像処理（動作検出）／自然言語処理
    image_url: https://user-images.githubusercontent.com/42331656/176980829-e4fb5bc7-1b30-405c-91b0-d99590270104.png
    tags:
      - Data Science
      - Framework
  - title: Rust
    description: |-
      興味のある言語です。
      [ls-improved](https://github.com/ShotaroKataoka/ls-Improved)の趣味開発で使用しました。
      WASMでの利用も興味あります。そのうち試してみたい。
    image_url: https://user-images.githubusercontent.com/42331656/168748889-8bcd4ec8-4894-416f-8b8f-8dbd4b8fedb4.png
    tags:
      - Programming language
  - title: Next.js
    description: |-
      3年程度の経験。個人開発・アルバイトで使用。
      このサイトを実装するにあたり勉強しました。
      言語はTypescriptをメインで使用。
    image_url: https://user-images.githubusercontent.com/42331656/168748817-f8bff2cc-d444-436c-86b1-fec14ea98bab.png
    tags:
      - Programming language
      - Framework
      - WEB
  - title: C / C++
    description: |-
      高専時代に3年程度の経験。マイコン開発で使用していました。
      C++は軽く触ったことがある程度です。
    image_url: https://user-images.githubusercontent.com/42331656/168736450-37093830-127a-41fb-ad6e-c0faaec9605e.jpg
    tags:
      - Programming language
  - title: Java
    description: |-
      大学の授業で習い、簡単なAndroidアプリを作成しました。
    image_url: https://user-images.githubusercontent.com/42331656/168748711-b1434155-d633-4d3f-8313-4928b6a2998c.png
    tags:
      - Programming language

works_data:
  - title: ls-improved
    description: |-
      **Rust**製のCLIツールです。ファイルやディレクトリに説明文を付与して `ls`ライクに一覧で表示します。
      機械学習などでパラメータを変えながら実験を繰り返すと似た名前のログが量産されてどの実験か一見して分からなくなるので，ファイルやディレクトリに直接説明を書き込めるツールが欲しくて開発しました。チーム開発においてもディレクトリ構成のメモを残せるということで結構便利に使えるようです。
      もともとPythonで開発してPyPIで配布していましたが、可搬性・処理速度の観点からバイナリ配布したかったのでRustに移植しました。
    image_url: https://user-images.githubusercontent.com/42331656/168714060-659821dc-310a-48e7-a972-a899c8d4af4f.jpg
    url: https://github.com/ShotaroKataoka/ls-Improved
  - title: Fuzzy-Explorer-on-Terminal
    description: |-
      **Bash / Zsh**製のCLIツールです。`FET`と呼んでいます。ターミナル上でのディレクトリ操作を直感的にサクサク行えるようにします。以下のような機能を構想し開発しています。
      - 矢印キーなどでの高速なディレクトリ移動
      - FET上での直感的な`cp`, `mv`, `rm`などのファイル操作
      - ディレクトリやファイルの**あいまい検索**
      - プラグインによる機能拡張
      
      まだalpha版なので環境によっては動かないことが（多々）あります。
    image_url: https://user-images.githubusercontent.com/42331656/168719866-b131b0f4-4687-4bbe-b075-2748f9615fed.jpg
    url: https://github.com/Fuzzy-Explorer/Fuzzy-Explorer-on-Terminal
  - title: RibbonCMS
    description: |-
      **Next.js／Python**製のコンテンツ管理システムです。GitHub Issuesの操作のみでブログや固定ページの投稿・更新ができることが特徴です。好きなテンプレートリポジトリをForkするだけでWEBページの見た目や構成をカスタマイズできます。
      テンプレートは自由に開発・配布できるので、**開発に興味がある方はぜひご連絡ください！！**
      （そのうちテンプレート集みたいなサイトを作ってそこで紹介したいと思っています）
    image_url: https://user-images.githubusercontent.com/42331656/168722759-38bce3a8-55fd-44d1-a992-9d2a73377087.png
    url: https://github.com/RibbonCMS
  - title: Fuzzy-Git-Operator
    description: |-
      **Bash / Zsh**製のCLIツールです。`FGO`と呼んでいます。[fzf](https://github.com/junegunn/fzf)で各種Git／GitHub操作を直感的に行えるようにします。また、コミットメッセージの絵文字プレフィックス入力を支援します。
      このツールがあまりにも便利すぎてGitスキルが鈍りそうなので、たまにFGO禁止縛りをしたりしています。
    image_url: https://user-images.githubusercontent.com/42331656/168720293-c1a9c0c3-85d8-482a-8b52-a38c80e3c175.jpg
    url: https://github.com/ShotaroKataoka/Fuzzy-Git-Operator
  - title: richcat
    description: |-
      **Python**製のCLIツールです。あらゆる形式のファイルをターミナル上で**Richにcat**することを目標に開発しています。
      マークダウンやシンタックス，CSV，Jupyter notebookなどを人に見やすい形式で表示することができます。
      主な開発者は[yamamoto-yuta](https://github.com/yamamoto-yuta)です。僕は設計の議論をしたりレビューしたりなコントリビュートで参加しています。
    image_url: https://user-images.githubusercontent.com/42331656/168721610-df26d91a-1883-4bd4-bae3-c3bbb6ae3114.jpg
    url: https://github.com/richcat-dev/richcat

time_line:
  - text: "**経歴**： [高知高専](https://www.kochi-ct.ac.jp/) 電気情報工学科卒業"
    date: 2018年3月
  - text: "**経歴**： 長岡技術科学大学 [情報経営システム工学課程](https://imse.nagaokaut.ac.jp/)3年次編入"
    date: 2018年4月
  - text: "**経歴**： 知識マイニング研究室 配属"
    date: 2018年9月
  - text: |-
      <font color='#E53E3E'>**実績**</font>： [学生表彰（課外活動）](https://www.nagaokaut.ac.jp/kosen/students/07.files/gakuseihyosyo_h30.pdf)
      ビジネスアイデアコンテストで優秀な成績を残したことについて学生表彰を受けた。
    date: 2019年3月
  - text: |-
      <font color='#E53E3E'>**実績**</font>： NEDO **未踏事業**[AIフロンティアプログラム](https://scrapbox.io/mitou-meikan/AI%E3%83%95%E3%83%AD%E3%83%B3%E3%83%86%E3%82%A3%E3%82%A2)に採択 *(2019.03 - 2020.02)*
      メンターの吉崎航さん(未踏スーパークリエータ／V-Sido OS開発者)の指導のもと、動画解析に関する研究開発に取り組んだ。
      また、プロジェクト成果が経産省から認められ<font color='#E53E3E'>**未踏AIフロンティアパスファインダー**</font>(未踏スーパークリエータ相当)として認定された。
      ![AIフロンティアプログラム成果報告会の様子](https://github.com/ShotaroKataoka/ShotaroKataoka.github.io/assets/42331656/a927bf63-f9a1-43e9-bef6-743850bc41c2)
    date: 2019年3月
  - text: |-
      <font color='#38A169'>**インターンシップ**</font>：[株式会社ソニーコンピュータサイエンス研究所](https://www.sonycsl.co.jp/) *(2019.07 - 2020.03)*
      **9ヶ月間**の長期にわたりリサーチアシスタントとしてオンサイトで勤務した。
      [コールセンターの業務効率改善AI](https://www.sonycsl.co.jp/press/prs20200702/)の研究開発チームでディープラーニング領域（NLP）の先行研究を担当し、BERTやGPT2等の応用可能性について検証を行った。
    date: 2019年7月
  - text: |-
      <font color='#E53E3E'>**活動**</font>：[長岡市長によるマカオ・深圳視察](https://www.city.nagaoka.niigata.jp/shityo/kaiken_i/file/20190823-3-1.pdf)に同行 (08.11 - 08.15)
      長岡市長とともにマカオで開かれた人工知能に関する学会[IJCAI-19](https://www.ijcai19.org/)及び、中国のシリコンバレーとも呼ばれる深圳市を視察した。
      深圳市ではITを活用したスマートな製造を進めている工場や、次々とベンチャー企業を生み出しているイノベーションセンターなどを視察することができた。
      ![視察の様子](https://github.com/ShotaroKataoka/ShotaroKataoka.github.io/assets/42331656/33ec8a55-5af1-4c3e-ba36-ef6a9b2dc360)
    date: 2019年8月
  - text: |-
      **経歴**： 長岡技術科学大学 [情報・経営システム工学課程](https://imse.nagaokaut.ac.jp/)修了
      <font color='#E53E3E'>**実績**</font>： [学生表彰（学業・研究活動）](https://www.nagaokaut.ac.jp/kosen/students/07.files/gakuseihyosyo_r1.pdf)
      学部成績優秀者として学生表彰を受けた。
    date: 2020年3月
  - text: |-
      **経歴**： 長岡技術科学大学 5年一貫制博士課程 [技術科学イノベーション専攻](http://sti.nagaokaut.ac.jp/)進学
      [卓越大学院プログラム](https://www.mext.go.jp/a_menu/koutou/kaikaku/takuetudaigakuin/index.htm)採択学生として、国からの支援のもとで研究を実施。
    date: 2020年4月
  - text: "<font color='#E53E3E'>**実績**</font>： 経済産業省委託事業の[L-Creator's Bridge](https://fairydevices.jp/news_20210308)にプロジェクトが採択され研究開発・成果報告を実施 *(2020.10 - 2021.01)*"
    date: 2020年10月
  - text: |-
      <font color='#38A169'>**アルバイト**</font>：[株式会社アイデミー](https://aidemy.net/) *(2020.11 - 2021.07 テクニカルサポート, 2021.07 - 現在 テックリード)*
      お客様からの技術的な質問（機械学習やPythonの理論・実装に関する質問）に対しての**テクニカルサポート**に従事。
      テクニカルサポート業務の傍ら**業務改革を提案・主導**し、**フルタイム2~3人分の稼働を削減**(稼働の30%程度に相当)することに成功した。
      この成果から、業務支援システム開発チーム(現在8名程度)を組織することが認められ、同チームの**テックリードとしてAIを活用したテクニカルサポート支援機能の設計・開発**に専従・挑戦している。
    date: 2020年11月
  - text: |-
      <font color='#38A169'>**インターンシップ**</font>： [株式会社ソニーコンピュータサイエンス研究所](https://www.sonycsl.co.jp/) *(2021.02 - 2022.07)*
      **1年6ヵ月間**の長期にわたりリサーチアシスタントとしてリモートで勤務した。
      [コールセンターの業務効率改善AI](https://www.sonycsl.co.jp/press/prs20200702/)の研究開発チームでディープラーニング領域（NLP）の先行研究を担当し、DPR等の応用可能性について検証を行った。
    date: 2021年2月
  - text: |-
      <font color='#E53E3E'>**実績**</font>： [株式会社マヨラボ](https://mayolab.co.jp)を起業／CEO就任
      AI技術の産業応用により人類の進歩を支えることを目指す大学発ベンチャー"株式会社マヨラボ"を設立。
      CEO兼開発リーダーとして複数企業との共同研究を進め、AIの社会実装に取り組んでいる。
      ![株式会社マヨラボ ロゴ](https://github.com/ShotaroKataoka/ShotaroKataoka.github.io/assets/42331656/d2b4ca91-1c80-4040-ba6f-d863f7605c01)
    date: 2021年2月
  - text: |-
      <font color='#E53E3E'>**実績**</font>：査読付き国際学術誌PLOSONEに主著論文が採択
      [Improving work detection by segmentation heuristics pre-training on factory operations video](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0267457)
      PLOSONE (IF: 3.752)
    date: 2022年6月
  - text: |-
      <font color='#E53E3E'>**実績**</font>： [新潟版未踏的人材育成事業ETSUZAN](https://etsuzan.org/) PM *(2023.07 - 2024.01)*
      地方版の未踏事業を目指して始まった経産省[AKATSUKIプロジェクト](https://mitouteki.jp/) - ETSUZANのプロジェクトマネージャーとして選任され、プロジェクト採択から伴走的支援まで携わった。
      チーム[nexfare](https://etsuzan.org/posts/nexfare)とチーム[Weareable](https://etsuzan.org/posts/Weareable)を採択し、半年間両チームのPMとしてサポートを行った。
      ![ETSUZANチーム紹介画像](https://github.com/ShotaroKataoka/ShotaroKataoka.github.io/assets/42331656/0b2008a2-265a-491b-bb92-4ab719f2ab09)
    date: 2023年7月
  - text: |-
      <font color='#38A169'>**インターンシップ**</font>： [国立研究開発法人理化学研究所](https://grp.riken.jp/labs/knowl_acqui_dialogue/) *(2023.09 - 2023.10)*
      GRP 知識獲得・対話研究チームで特許分野の大規模視覚言語モデル開発に取り組み、研究計画・データセット作成・モデル学習準備までを担当。
    date: 2023年9月
  - text: |-
      <font color='#E53E3E'>**実績**</font>：**クラウドファンディングを実施＆3日間で目標金額達成**
      日常の"動き"に音楽を融合する[ウェアラブル楽器デバイス Synthevery](https://www.indiegogo.com/projects/synthevery-a-new-instrument-all-u-need-is-motion/x/36534099#/)
      ETSUZANでPMを担当したプロジェクトのクラウドファンディングをIndiegogoで実施し、開始3日間で目標金額を達成した。
      <div style="display: flex; justify-content: center; width: 100%;"><div style="position: relative; width: 100%; max-width: 560px; height: 0; padding-bottom: 56.25%;"><iframe src="https://www.youtube.com/embed/ggNu_f9FkfU?si=7CHpTHZhb-jfyii3&rel=1" title="YouTube video player" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div></div>
    date: 2024年1月
```
