### ISSUE TITLE
Index

### ISSUE THREAD

**Issue by ShotaroKataoka** [ShotaroKataoka/ShotaroKataoka.github.io#4]
```yaml
site_description: |-
    ## ブログの方針
    ブログの内容は**個人的なもので所属組織などに一切関係しません**。

    やったことや考えたことなどをメモがてら書いていきます。
    ほぼSNSとか日記みたいな感じになると思うので見に来てもしょうがないかも。

    ↓のことに興味があります。
    - AI／プログラミングなど技術関係
    - ボードゲーム／推理・謎解き／リアル脱出ゲーム
    - 開発環境カスタマイズ／VIM／Linux
    - VR・AR／デバイス
    - カラオケ

    ## このサイトの紹介
    このサイトは私が開発している[RibbonCMS](https://github.com/RibbonCMS/RibbonCMS)で作成しました。
    RibbonCMSはGitHub操作のみで運用可能なコンテンツ管理システムで、編集インターフェースとしてGitHub Issuesを採用しています。
    Issueを投稿・編集することで、記事の投稿や固定ページの編集をすることができます。
    コンテンツ管理システムとフロントエンド機能が分離しているため、任意のフロントエンドデザインを自作可能です。
    完全に無料でブログ運営をしたい人／フロントエンドをゴリゴリに自作したい人／クラウドサーバを使うのがめんどくさい人におすすめです。
site_header_title: ".github.io"
```
