### ISSUE TITLE
汎用版RibbonCMS完成！

### ISSUE THREAD

**Issue by ShotaroKataoka** [ShotaroKataoka/ShotaroKataoka.github.io#5]
```yaml
# OGP description. 記事の概要．
ogp_description: GitHub Issuesだけでブログを作成・更新・公開できるコンテンツ管理システム「RibbonCMS」のアルファ版が完成しました！今回はその特徴や使い方をご紹介します！

# OGP image. OGP画像のテーマ設定 = 'default' | Image URL
ogp_img_theme: default

# 予約投稿の日時(投稿したい日時を記載)
#posted_at: 2022年06月24日 09時00分
```
かたおかです。
思ったより時間がかかりましたが、**汎用版RibbonCMS**のアルファ版が完成しました。
まだまだ開発・改良の余地はありますが、一応形にはなったのでご紹介していきます。

## RibbonCMS
[RibbonCMS](https://github.com/RibbonCMS/RibbonCMS)とは**GitHub Issuesの操作だけでホームページを管理・更新するコンテンツ管理システム**です。
このブログもRibbonCMSを使って更新しています。
<br/>

はじめはこのブログを管理するためだけに開発していたため、
ホームページの見た目やサイト構成などが固定されていました。
しかし、せっかくなら「**誰でもどんなサイトでも使える**」と面白いなと思い、汎用版RibbonCMSの開発を始めました。
<br/>

RibbonCMSは以下の特徴を持ちます。
- GitHub Issuesで**記事の執筆**ができる。
- GitHub Issuesで**サイト設定の管理**ができる。
- GitHub Issuesで**固定ページ内容の編集**ができる。
- 「Issueからのコンテンツ生成」「コンテンツ管理」「コンテンツからのサイト生成（フロントエンド）」の**機能が分離**している。
  - フロントエンドを自作したり、他の人が作ったテンプレートを使ったりなど容易にカスタマイズできる。
  - Issueからコンテンツを生成する機能も部分的にプラグインを導入できるようにしているのでカスタマイズ可能。

編集中．．．
